### PR TITLE
reduce object creation by useMemo

### PR DESCRIPTION
**Pull request by leoyli**
Hi, thank you for creating this amazing library!

I've noticed there are some performance improvements can be done by using `useMemo` in `useEventCallback` hook.  The change basically leverage the lazy evaluations and reduce new object creations at run-time.

Thank you!

### CODE REVIEW

**Comment by Brooooooklyn** [comment]
Please squash your commits, and edit your commit follow the guide: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines

**Comment by leoyli** [comment]
@Brooooooklyn, thanks fixed.

**Comment by Brooooooklyn** [comment]
unit test failed in circle @leoyli

**Comment by leoyli** [comment]
@Brooooooklyn, is that due to the code is running under react 16.9, based on the release post, there are some change in the testing utility?!  I changed nothing but squash my commits, last time it passed.

**Comment by Brooooooklyn** [comment]
It's React 16.9 already in master branch, and all tests were passed.
So could you please double check your changes and pass the tests in your local machine?

**Comment by BlackHole1** [comment]
@leoyli @Brooooooklyn  Change the code to the following to pass the test:

```diff
- const returnedCallback = useCallback((e: EventValue) => event$.next(e), [event$])
+ function eventCallback(e: EventValue) {
+    return event$.next(e)
+ }
+ const returnedCallback = useCallback(eventCallback, [event$])
```

https://github.com/LeetCode-OpenSource/rxjs-hooks/pull/65/files#diff-a4eb4268013ae7511c07e3266bf23937R62

**Comment by Miloas** [comment]
Closed because of https://github.com/LeetCode-OpenSource/rxjs-hooks/commit/9b866983c92cbe52318cc82b9f4ff14c3515645e

**Pull request closed without merging**
